### ISSUE TITLE
What recognizes geo:// ?

### ISSUE THREAD

**Issue by ocdtrekkie** [orblivion/sandstorm-share-a-map#2]
On both my Firefox at home, and Safari on my phone, clicking the new geo:// link results in an error. I am not sure this is a widely recognizes protocol for links, but I am interested in seeing how I can use it. It might be worthwhile to note some example apps which support this feature.

**Comment by orblivion** [comment]
Hmm, dang. I was hoping it would be standard enough.

It works for me on Chromium on Android (well, technically Vanadium on
GrapheneOS). It offers to open in my various map applications. OrganicMaps
and OSMAnd both do what I expect. I also tried on iPad, Safari I believe.
It opened in OrganicMaps as well, though it didn't even offer to try on
Apple Maps.

Firefox on desktop doesn't do anything if Gnome Maps isn't installed. If I
install it, Firefox gives me a generic "pick an application" menu, and
"Maps" is the only option. And it works.

So bottom line - maybe on all platforms, it all has to do with what Map
applications you have installed?

I was hoping this would be smoother than the kmz export. I tried that on a
group of people recently and none of them got anything out of it. Maybe kmz
export/import has the same restriction as geo:// - it needs to have the
right sort of map application installed, and maybe the major map
applications don't support it.

kmz and/or geo:// may not be *essential*, but I think it could make a big
difference in usability and adoption. Ultimately I'd like users to be able
to receive a link to a map, make one or two clicks, and then be able to
navigate to the bookmarked locations. Otherwise the app is kind of just a
novelty. Maybe with the right sort of UI it could at least point people
toward installing the right sort of map app?

Thank you for trying it out!

**Comment by orblivion** [comment]
I think there may be some other things akin to geo:// that work on Apple
Maps or Google Maps.

...then again, maybe I don't want to encourage those, heh. Or at least give
a warning, since it sacrifices some privacy that was gained by using
Share-A-Map to begin with.

**Comment by ocdtrekkie** [comment]
Intriguingly, OsmAnd is available for iOS (despite "And" referring to Android), but does not accept the geo:// command. Organic Maps does work though, I can confirm that.

For what it's worth, Apple Maps and Google Maps have radically different data security policies, and I'm pretty comfortable with Apple's, at this time: https://www.apple.com/legal/privacy/data/en/apple-maps/ (tl;dr: Location data is never associated with your account, and deliberately obfuscated. If you choose to use your Apple ID to sync data, it uses end-to-end encryption between devices for that information.) Most functionality of Google Maps doesn't work at all unless you enable Location History, which stores your precise location information in your Google account.

**Comment by orblivion** [comment]
Okay, thanks for looking into that. That's a fair point about security
policies. Users can have their own preferences.

In the short run, do you feel like this feature would make sense with a
caveat? "Open in external app (depending on your setup. [Learn More])". And
then over time I could look into more protocols, like map://.

In the long run it would be nice if we could somehow detect client-side if
geo:// would work on the given system. Seems like there's maybe something
doable on this front, looking at the comments here
https://stackoverflow.com/questions/19787100/detecting-geo-uri-support.
I'll add it to post-release TODOs.

**Comment by ocdtrekkie** [comment]
Yeah I think it's useful, it just was confusing to get an error on both platforms I use when trying it.

**Comment by orblivion** [comment]
Closing this issue in favor of more specific #13 #14 and #15.
